# Generated by Django 4.1.7 on 2023-04-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empt',
            name='DEPTNO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept'),
        ),
    ]
